package:
  name: suds-jurko
  version: {{version}}

source:
  fn: suds-jurko-{{version}}.tar.bz2
  url: https://pypi.python.org/packages/source/s/suds-jurko/suds-jurko-{{version}}.tar.bz2
  md5: {{md5}}

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - suds
    - suds.bindings
    - suds.mx
    - suds.sax
    - suds.transport
    - suds.umx
    - suds.xsd
    - tests
    - tests.external

about:
  home: http://bitbucket.org/jurko/suds
  license:  GNU Library or Lesser General Public License (LGPL)
  summary: "Lightweight SOAP client (Jurko's fork)"

